language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: UT17jCvitnZ/uKr3MfEmoIwEFkmHRtvgnxdxlTxcsWSdKgSlXxiVOdB3seSll6fjhq1+i4Ik7GOSW8ZnSGfKZNRj51d3lhepqtpj4upLXeBWrkjgvuITtfUf3Ze3WNQTWONUhxBI82NbsXoGY0DM1thPw+5jAH8ZTlK5JA9WOlLjzroO/k1FEXFVULkWBn00sxND55gp83q4KZG1rDPLezIC6zy6yRqttHebAkojsVyt4Xi9v0Nl2LpET56MjJhOGs1Iiqy1QDGVLrwjWjgNGUHD4C7PNeM+ENAACHO94bb2yzJ8KvM+mB6dm7/hNmctEZw2fPyyd25Vd2KvHr/GqsXf3kGlGBYiSHvtFyZ5+ZY7UgpoF2kugUcGDjaSknOSCzk0pWe5W57d4SzPnxBWhvznyFydGVp23AV9HU8E+okipBJ6Ltlvgo3uRwZ+fbQwLuGIut/lYbDgPRZF2j3QsQbgE/0CEFRck7iNrSzcYo4hsJr+OJt1+LNqFYGFNJS59ZR4SrNHsiDSNzCliPbYY9MOTPRX3FlXd8/5uj2DSaCenNXiLDalVKHAFLrMAb4CXx3f6HPp8WF36wBMBaU9oCHm8oR0B2ueAeCGUilbzhYCEfZLjpr106vBIZx1PeZlzDlIoKGSmYIhveG8T2jW4pf4Eqzl1h8vr4Cfs52KnC4=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
